---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      time: "04:00"
      timezone: Europe/Vienna
      interval: weekly
    groups:
      deps:
        patterns:
          - '*'
